apiVersion: v1
kind: Namespace
metadata:
  name: tls
---
apiVersion: v1
kind: Pod
metadata:
  name: etcd
  namespace: tls
  labels:
    role: config
spec:
  containers:
    - name: etcd
      image: bitnami/etcd:3.5.7
      ports:
        - containerPort: 2379
      env:
        - name: ETCD_TRUSTED_CA_FILE
          value: /etc/ssl/private/ca.crt
        - name: ETCD_CERT_FILE
          value: /etc/ssl/private/tls.crt
        - name: ETCD_KEY_FILE
          value: /etc/ssl/private/tls.key
        - name: ETCD_ROOT_PASSWORD
          value: whatever
        - name: ETCD_CLIENT_CERT_AUTH
          value: "true"
        - name: ETCD_LISTEN_CLIENT_URLS
          value: https://0.0.0.0:2379
      volumeMounts:
        - name: ssl
          mountPath: /etc/ssl/private
  volumes:
    - name: ssl
      secret:
        secretName: etcd-secret
---
kind: Service
apiVersion: v1
metadata:
  name: etcd
  namespace: tls
spec:
  ports:
    - port: 2379
  selector:
    role: config
